# Generated by Django 3.1.2 on 2020-10-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20201020_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callstack',
            old_name='url',
            new_name='path',
        ),
    ]
