# Generated by Django 3.1.2 on 2020-10-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_fileext_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileext',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
