# Generated by Django 3.1.4 on 2020-12-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20201027_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='sudo',
        ),
    ]
