# Generated by Django 3.1.4 on 2020-12-15 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_remove_repository_sudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='repository.repository', verbose_name='Repository')),
            ],
            options={
                'verbose_name': 'Repository Size',
                'verbose_name_plural': 'Repository Sizes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
