# Generated by Django 3.1.4 on 2020-12-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_reposize'),
    ]

    operations = [
        migrations.AddField(
            model_name='reposize',
            name='size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Size'),
            preserve_default=False,
        ),
    ]
