# Generated by Django 3.2 on 2021-04-09 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_reposize_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reposize',
            options={'ordering': ['timestamp'], 'verbose_name': 'Repository Size', 'verbose_name_plural': 'Repository Sizes'},
        ),
    ]
