# Generated by Django 4.0.5 on 2022-06-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0017_repository_extra_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='reposize',
            name='file_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='File count'),
            preserve_default=False,
        ),
    ]
