# Generated by Django 4.0.5 on 2022-06-22 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0018_reposize_file_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reposize',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.repository', verbose_name='Repository'),
        ),
    ]
