# Generated by Django 4.0.7 on 2022-08-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0019_alter_reposize_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetype',
            name='svg_path',
            field=models.CharField(max_length=1000, verbose_name='SVG Path'),
        ),
    ]
