# Generated by Django 4.0.7 on 2022-12-31 11:04

from django.db import migrations
import encrypted_json_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0019_alter_reposize_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='extra_keys',
            field=encrypted_json_fields.fields.EncryptedJSONField(blank=True, default=dict, help_text="List KEY=VALUE pairs to be added to the env when connecting with this repo; place each key/value pair on it's own line"),
        ),
    ]
