# Generated by Django 4.1.4 on 2022-12-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0020_alter_filetype_svg_path'),
        ('repository', '0020_alter_repository_extra_keys'),
    ]

    operations = [
    ]
